fedlocal:
    container_name: fedlocal
    image: learninglayers/fedlocal
    expose:
        - "8080"
        - "9012/tcp"
        - "9012/udp"

fedlocalfrontend:
    container_name: fedlocalfrontend
    image: learninglayers/fedlocalfrontend